//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace donationrequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForeignCourse
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Institution { get; set; }
    
        public virtual Institution Institution1 { get; set; }
    }
}
