//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace donationrequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class JunctionEq
    {
        public int ID { get; set; }
        public string ForeignCourse { get; set; }
        public string TTUCourse { get; set; }
        public Nullable<bool> Static { get; set; }
    }
}
